import { copyFileSync, mkdirSync } from "fs";
import { dirname, resolve, basename } from "path";
import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";

const isProd = process.env.BUILD === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the github repository of this plugin
*/
`;

function copyFiles(targets) {
    return {
        name: "copy-files",
        writeBundle() {
            for (const { src, dest } of targets) {
                const destPath = resolve(dest, basename(src));
                mkdirSync(dirname(destPath), { recursive: true });
                copyFileSync(src, destPath);
            }
        },
    };
}

export default {
    input: "src/main.ts",
    output: {
        file: "dist/obsidian-vault-sync/main.js",
        sourcemap: "inline",
        sourcemapExcludeSources: isProd,
        format: "cjs",
        exports: "default",
        banner,
        inlineDynamicImports: true,
    },
    external: ["obsidian", "fs", "os", "path", "child_process"],
    plugins: [
        typescript(),
        nodeResolve({ browser: true }),
        commonjs(),
        copyFiles([
            { src: "manifest.json", dest: "dist/obsidian-vault-sync" },
            { src: "src/styles.css", dest: "dist/obsidian-vault-sync" },
        ]),
    ],
};
