import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import copy from "rollup-plugin-copy";

const isProd = process.env.BUILD === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the github repository of this plugin
*/
`;

export default {
    input: "src/main.ts",
    output: {
        file: "dist/main.js",
        sourcemap: "inline",
        sourcemapExcludeSources: isProd,
        format: "cjs",
        exports: "default",
        banner,
        inlineDynamicImports: true,
    },
    external: ["obsidian"],
    plugins: [
        typescript(),
        nodeResolve({ browser: true }),
        commonjs(),
        copy({
            targets: [
                { src: "manifest.json", dest: "dist" },
                { src: "src/styles.css", dest: "dist" },
            ],
        }),
    ],
};
