import { copyFileSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, resolve, basename } from "path";
import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import terser from "@rollup/plugin-terser";

const isProd = process.env.BUILD === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the github repository of this plugin
*/
`;

function minifyCss(css) {
    return css
        .replace(/\/\*[\s\S]*?\*\//g, "")
        .replace(/\s+/g, " ")
        .replace(/\s*([{}:;,>~+])\s*/g, "$1")
        .replace(/;}/g, "}")
        .trim();
}

function copyFiles(targets) {
    return {
        name: "copy-files",
        writeBundle() {
            for (const { src, dest } of targets) {
                const destPath = resolve(dest, basename(src));
                mkdirSync(dirname(destPath), { recursive: true });
                if (isProd && src.endsWith(".css")) {
                    const raw = readFileSync(src, "utf8");
                    writeFileSync(destPath, minifyCss(raw));
                } else {
                    copyFileSync(src, destPath);
                }
            }
        },
    };
}

export default {
    input: "src/main.ts",
    output: {
        file: "dist/obsidian-vault-sync/main.js",
        sourcemap: isProd ? false : "inline",
        sourcemapExcludeSources: true,
        format: "cjs",
        exports: "default",
        banner,
        inlineDynamicImports: true,
    },
    external: ["obsidian", "fs", "os", "path", "child_process"],
    plugins: [
        typescript(),
        nodeResolve({ browser: true }),
        commonjs(),
        terser(),
        copyFiles([
            { src: "manifest.json", dest: "dist/obsidian-vault-sync" },
            { src: "src/styles.css", dest: "dist/obsidian-vault-sync" },
            { src: "src/i18n/lang/ja.json", dest: "dist/obsidian-vault-sync/lang" },
        ]),
    ],
    treeshake: true,
};
